### PR TITLE
cannot be installed with npm

### PR DESCRIPTION
**Pull request by jwchang0206**
I cannot install this module with npm

I got this message

``` bash
npm ERR! fetch failed https://registry.npmjs.org/primus-express-session/-/primus-express-session-0.0.1.tgz
npm ERR! Error: 404 Not Found
```

### CODE REVIEW

**Comment by zemirco** [comment]
That's funny! 

I'm sorry but I can't reproduce your issue. You might have to download the code manually by cloning this repo and putting it in your `node_modules/` folder.

**Comment by jwchang0206** [comment]
I use primus version of 2.0.4 now and the dependency primus version is 1.x for this module causes the installation problem.

The problem is solved by bump up the primus version.

Since the test are passing, it would be okay to bump up the version.

**Comment by zemirco** [comment]
I don't think bumping the primus version will solve `npm ERR! Error: 404 Not Found` but I've updated the dependencies and released `0.0.2`.

Please try the new version. Do you still get the error?

**Comment by jwchang0206** [comment]
New version is okay with me :+1:

**Pull request closed without merging**
